// Fastify plugin autogenerated by fastify-openapi-glue
const openapiGlue = require("fastify-openapi-glue");

const options = {
  specification: `${__dirname}/openApi.json`,
  service: `${__dirname}/service.js`,
  noAdditional: true,
};

module.exports = async function (fastify, opts) {
  fastify.register(openapiGlue, options);
};
